import React, { useState } from 'react'; 
import Head from 'next/head';
import styles from '@/styles/EditWeek.module.scss';
import Image from 'next/image';

const pseudoResults = [
  {
    "Title": "The Avengers",
    "Year": "2012",
    "imdbID": "tt0848228",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg"
  },
  {
    "Title": "Avengers: Endgame",
    "Year": "2019",
    "imdbID": "tt4154796",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg"
  },
  {
    "Title": "Avengers: Infinity War",
    "Year": "2018",
    "imdbID": "tt4154756",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg"
  },
  {
    "Title": "Avengers: Age of Ultron",
    "Year": "2015",
    "imdbID": "tt2395427",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg"
  },
  {
    "Title": "The Avengers",
    "Year": "1998",
    "imdbID": "tt0118661",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BYWE1NTdjOWQtYTQ2Ny00Nzc5LWExYzMtNmRlOThmOTE2N2I4XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg"
  },
  {
    "Title": "Ultimate Avengers: The Movie",
    "Year": "2006",
    "imdbID": "tt0491703",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTYyMjk0NTMwMl5BMl5BanBnXkFtZTgwNzY0NjAwNzE@._V1_SX300.jpg"
  },
  {
    "Title": "Ultimate Avengers II",
    "Year": "2006",
    "imdbID": "tt0803093",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BZjI3MTI5ZTYtZmNmNy00OGZmLTlhNWMtNjZiYmYzNDhlOGRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"
  },
  {
    "Title": "Next Avengers: Heroes of Tomorrow",
    "Year": "2008",
    "imdbID": "tt1259998",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTQ3NjExNjY4N15BMl5BanBnXkFtZTcwNTczODkwNQ@@._V1_SX300.jpg"
  },
  {
    "Title": "Avengers Confidential: Black Widow & Punisher",
    "Year": "2014",
    "imdbID": "tt3482378",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTU2MDg0Njk4MF5BMl5BanBnXkFtZTgwMTY0OTIyMTE@._V1_SX300.jpg"
  },
  {
    "Title": "Crippled Avengers",
    "Year": "1978",
    "imdbID": "tt0077292",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BOTgzMjMxOTYtYzQzZi00NWM1LTljZDMtN2UwZWE3MjlhZDdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"
  }
];

const emptyPicks = [
  {
    "Title": "The Avengers",
    "Year": "2012",
    "imdbID": "tt0848228",
    "Type": "movie",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    "service" : ""
  },
  false,
  false,
]

export default function EditWeek(){
  const [searchTerm, setSearchTerm ] = useState('');
  const [searchResults, setSearchResults ] = useState(pseudoResults);
  const [picks, setPicks ] = useState(emptyPicks);
  const addPick = (id) => {
    return () => {
      const picksCopy = [...picks];
      const pick = searchResults.find((movie) => movie.imdbID === id);
      const blankIndex = picksCopy.indexOf(false);
      if(blankIndex === -1 || !pick){ return; }
      picksCopy[blankIndex] = {
        ...pick,
        service: ''
      };
      setPicks(picksCopy);
    }
  }
  const removePick = (id) => {
    return () => {
      setPicks(picks.map((movie) => {
        if(!movie){ return false; }
        if(movie.imdbID === id){ return false; }
        return movie;
      }));
    }
  };
  return (
    <>
     <Head>
        <title>Best Friends Movie Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.header}>
          <div className={styles.header__marquee}>
            <h1 className={styles.header__title}>
              B<span className={styles.hideMobile}>est </span>
              F<span className={styles.hideMobile}>riends </span> 
              M<span className={styles.hideMobile}>ovie </span> 
              C<span className={styles.hideMobile}>lub</span> 
            </h1>
          </div>
        </header>
        <article className={styles.card}>
          <div className={styles.searchForm}>
            <h2>Manage Week: 998</h2>
            <p>
              <label htmlFor='search'>Find A Movie</label>
              <input type='text' name='search' className={styles.searchField} placeholder='Movie Title' value={searchTerm} onChange={({target}) => { setSearchTerm(target.value)}} />
              <button type='button' className={styles.searchButton}>Search</button>
            </p>
            <p>{searchTerm}</p>
            <div className={styles.picks}>
              <h3>Picks</h3>
              <ul className={styles.picksList}>
                {picks.map((pick, index) => {
                  return pick? (
                    <li key={pick.imdbID} className={styles.picksList__item}>
                      <h3 className={styles.picksList__item_headline}>Pick {index + 1}</h3>
                      <Image  src={pick.Poster} width={300} height={450} className={styles.picksList__poster} alt={`${pick.Title} - ${pick.Year}`} />
                      <div className={styles.picksList__item_info}>
                        <div className={styles.picksList__item_title}>{pick.Title} ({pick.Year})</div>
                        <label className={styles.picksList__item_service}>
                          Service: 
                          <select>
                            <option value=""></option>
                            <option value="HBO">HBO Max</option>
                            <option value="AMAZON">Amazon Prime</option>
                          </select>
                        </label>
                      </div>
                      <div className={styles.picksList__item_clear} onClick={removePick(pick.imdbID)}>&times;</div>
                    </li>
                  ) : (
                    <li key={index} className={styles.picksList__item}>
                      <h3 className={styles.picksList__item_headline}>Pick {index + 1}</h3>
                      <Image  src='/img/no-poster.png' width={300} height={450} className={styles.picksList__poster} alt={'No Poster'} />
                    </li>
                  )
                })}
              </ul>
            </div>
          </div>
          <aside className={styles.searchResults}>
            <h3>Search Results</h3>
            <ul className={styles.searchResults__list}>
              {searchResults.map((result) => (
                <li className={styles.searchResults__item} key={result.imdbID} onClick={addPick(result.imdbID)}>
                  <Image src={result.Poster} width={300} height={450} className={styles.searchResults__poster} alt={`${result.Title} - ${result.Year}`} />
                  <h4 className={styles.searchResults__title}>
                    <span>{result.Title} ({result.Year})</span>
                  </h4>
                </li>
              ))}
            </ul>
          </aside>
        </article>
      </main>
    </>
  )
}