import React, { useState } from 'react'; 
import Head from 'next/head';
import styles from '@/styles/EditWeek.module.scss';
import Image from 'next/image';
import axios from 'axios';

export default function EditWeek(){
  const [searchTerm, setSearchTerm ] = useState('');
  const [searchResults, setSearchResults ] = useState([]);
  const [picks, setPicks ] = useState([false, false, false]);

  async function search(){
    if(searchTerm === ''){ return; }
    try{
      const { data } = await axios.get(`/api/search-movie?title=${encodeURIComponent(searchTerm)}`);
      setSearchResults(data.movies)
    } catch (error) {
      setSearchResults([]);
    }
  }
  const typeSearch = ({ code }) => {
    if(code === 'Enter'){
      search();
    }
  }
  const addPick = (id) => {
    return () => {
      const picksCopy = [...picks];
      const pick = searchResults.find((movie) => movie.imdbID === id);
      const blankIndex = picksCopy.indexOf(false);
      if(blankIndex === -1 || !pick){ return; }
      if(picks.find((movie) => movie.imdbID === id)){ return; }
      picksCopy[blankIndex] = {
        ...pick,
        service: ''
      };
      setPicks(picksCopy);
    }
  }
  const setService = (id) => {
    return ({target}) => {
      setPicks(picks.map((pick) => {
        if(!pick || pick.imdbID !== id){ return pick; }
        return {
          ...pick,
          service: target.value
        };
      }));
    };
  }
  const removePick = (id) => {
    return () => {
      setPicks(picks.map((movie) => {
        if(!movie){ return false; }
        if(movie.imdbID === id){ return false; }
        return movie;
      }));
    }
  };
  return (
    <>
     <Head>
        <title>Best Friends Movie Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.header}>
          <div className={styles.header__marquee}>
            <h1 className={styles.header__title}>
              B<span className={styles.hideMobile}>est </span>
              F<span className={styles.hideMobile}>riends </span> 
              M<span className={styles.hideMobile}>ovie </span> 
              C<span className={styles.hideMobile}>lub</span> 
            </h1>
          </div>
        </header>
        <article className={styles.card}>
          <div className={styles.searchForm}>
            <h3>Search</h3>
            <p>
              <input type='text' name='search' className={styles.searchField} placeholder='Movie Title' value={searchTerm} onChange={({target}) => { setSearchTerm(target.value)}} onKeyUp={typeSearch} />
              <button type='button' className={styles.searchButton} onClick={search}>Search</button>
            </p>
            <div className={styles.picks}>
              <h4>Picks</h4>
              <ul className={styles.picksList}>
                {picks.map((pick, index) => {
                  return pick? (
                    <li key={pick.imdbID} className={styles.picksList__item}>
                      <h3 className={styles.picksList__item_headline}>Pick {index + 1}</h3>
                      <Image  src={pick.Poster} width={300} height={450} className={styles.picksList__poster} alt={`${pick.Title} - ${pick.Year}`} />
                      <div className={styles.picksList__item_info}>
                        <div className={styles.picksList__item_title}>{pick.Title} ({pick.Year})</div>
                        <label className={styles.picksList__item_service}>
                          Service: 
                          <select onChange={setService(pick.imdbID)} value={pick.service}>
                            <option value=""></option>
                            <option value="HBO">HBO Max</option>
                            <option value="AMAZON">Amazon Prime</option>
                          </select>
                        </label>
                      </div>
                      <div className={styles.picksList__item_clear} onClick={removePick(pick.imdbID)}>&times;</div>
                    </li>
                  ) : (
                    <li key={index} className={styles.picksList__item}>
                      <h3 className={styles.picksList__item_headline}>Pick {index + 1}</h3>
                      <Image  src='/img/no-poster.png' width={300} height={450} className={styles.picksList__poster} alt={'No Poster'} />
                    </li>
                  )
                })}
              </ul>
            </div>
            <div className={styles.pickButtons}>
              <button disabled>Save</button>
              <button disabled>Send Out</button>
            </div>
          </div>
          <aside className={styles.searchResults}>
            <h3>Results</h3>
            <ul className={styles.searchResults__list}>
              {searchResults.map((result) => (
                <li className={styles.searchResults__item} key={result.imdbID} onClick={addPick(result.imdbID)}>
                  <Image src={result.Poster === 'N/A'? '/img/no-poster.png' : result.Poster} width={300} height={450} className={styles.searchResults__poster} alt={`${result.Title} - ${result.Year}`} />
                  <h4 className={styles.searchResults__title}>
                    <span>{result.Title} ({result.Year})</span>
                  </h4>
                </li>
              ))}
            </ul>
          </aside>
          <aside className={styles.settings}>
            <h3>Settings</h3>
            <p>Coming Soon</p>
          </aside>
        </article>
      </main>
    </>
  )
}