import Head from 'next/head';
import { MovieCard } from 'components';
import styles from '@/styles/Home.module.scss';
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

  export async function getServerSideProps(){
    const week = await prisma.week.findFirst({
      where: {
        id: 1
      },
      include: {
        picker: true,
        movies: {
          include: {
            movie: true,
            vote: {
              include: {
                user: true
              }
            },
          }
        }
      }
    });
    const data = JSON.parse(JSON.stringify(week));
    const { movies, picker } = data;
    return {
      props: {
        data,
        week: {
          number: data.number,
          date: 'Dec 31',
          picker: picker.name,
          pickerId: picker.id
        },
        movies
      }
    }
  }
  
  export default function CurrentWeek({ week, movies }) {
    return (
      <>
        <Head>
          <title>Best Friends Movie Club</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header}>
          <div className={styles.header__marquee}>
            <h1 className={styles.header__title}>
              B<span className={styles.hideMobile}>est </span>
              F<span className={styles.hideMobile}>riends </span> 
              M<span className={styles.hideMobile}>ovie </span> 
              C<span className={styles.hideMobile}>lub</span> 
            </h1>
            <div className={styles.header__info}>
              <div className={styles.header__week}><span className={styles.hideMobile}>Now Playing: </span>Week {week.number}</div>
              <div className={styles.header__picker}>{week.picker}</div>
              <div className={styles.header__time}>{week.date} - 7:15 CST / 5:15 PST</div>
            </div>
          </div>
        </header>
        <main className={styles.movies}>
          {
            movies.map((movie) => (
              <MovieCard key={movie.id} movie={movie} />
            ))
          }
        </main>
      </>
    )
}
