import Head from 'next/head';
import styles from '@/styles/EditWeek.module.scss';
import { Card } from '@/design-system';
import { SearchForm, SearchResults, PicksList } from '@/features/MoviePicker/components'
import { WeekSettings } from '@/features/WeekSettings/components';
import { getUserWeek } from '@/data';
import { MovieSearchProvider } from '@/features/MoviePicker/context/Provider';
import { WeekSettingsProvider } from '@/features/WeekSettings/context/Provider';

export async function getServerSideProps(ctx){
  return {
    props: { 
      ...(await getUserWeek(ctx)),
      page: 'week'
    }
  };
}

export default function EditWeek({ week, users }){  
  const initialSearch = {
    searchString: '',
    isVotingWeek: true,
    isSearchLoading: false,
    searchResults: [],
    searchError: '',
    picks: [
      ...week.movies.map(movie => ({
        Poster: movie.movie.poster,
        Title: movie.movie.title,
        Year: movie.movie.year,
        imdbID: movie.movieId,
        loading: false,
        service: movie.service,
        serviceLink: movie.link
      })),
      false,
      false,
      false
    ].slice(0,3),
  };
  const initialSettings = {
    date: week.dateVal,
    attendees: users.filter((user) => (!week.absentees.find((abs) => abs.userId === user.id))),
    absentees: week.absentees.map(absentee => absentee.user),
    commentary: week.note,
    users: users
  };

  return (
    <>
     <Head>
        <title>Best Friends Movie Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Card className={styles.card}>
          <MovieSearchProvider initialValue={initialSearch}>
            <SearchForm />
            <PicksList />
            <SearchResults />
          </MovieSearchProvider>
          <WeekSettingsProvider initialValue={initialSettings}>
            <WeekSettings />
          </WeekSettingsProvider>
        </Card>
      </main>
    </>
  )
}